#define LOCK_PROTOTYPE CK_RW_COHORT_WP_PROTOTYPE
#define LOCK_INSTANCE CK_RW_COHORT_WP_INSTANCE
#define LOCK_INITIALIZER CK_RW_COHORT_WP_INITIALIZER
#define READ_LOCK CK_RW_COHORT_WP_READ_LOCK
#define WRITE_LOCK CK_RW_COHORT_WP_WRITE_LOCK
#define READ_UNLOCK CK_RW_COHORT_WP_READ_UNLOCK
#define WRITE_UNLOCK CK_RW_COHORT_WP_WRITE_UNLOCK
/*
#define WRITE_LOCK(N, RW, C, GC, LC)\
	CK_RW_COHORT_WP_WRITE_LOCK(N, RW, C, GC, LC)

#define WRITE_UNLOCK(N, RW, C, GC, LC)\
	CK_RW_COHORT_WP_WRITE_UNLOCK(N, RW, C, GC, LC);

#define READ_LOCK(N, RW, C, GC, LC)\
	CK_RW_COHORT_WP_READ_LOCK(N, RW)
*/