env:
  CIRRUS_CLONE_DEPTH: 1

task:
  matrix:
   - name: freebsd13-amd64
     freebsd_instance:
       image_family: freebsd-13-3
   - name: freebsd14-amd64
     freebsd_instance:
       image_family: freebsd-14-0
   - name: linux-arm64
     arm_container:
       image: ubuntu:latest
     setup_script: |
       apt-get update
       apt-get install -y gcc make
  script:
   - cc --version
   - ./tools/ci-build.sh --cores=2
   - make check
