#!/bin/sh

if [ $# -ne 1 ]
then
	echo "Usage: $0 <common repo directory>"
	exit
fi

commondir=$1
toolsdir=`dirname $0`
srcdir=`dirname $toolsdir`
src=$srcdir/include
trg=$commondir/src/include/aerospike/ck

cd $src
rm -rf $trg
mkdir -p $trg

find . -type f -name "*.h" -exec $toolsdir/transform_header {} $trg \;
